import {
  ALARM_CURRENT_SERVER,
  ALARM_HISTORY_SERVER,
  DEVICE_SERVER,
  LOCK_SERVER,
  LOG_SERVER,
  STRATEGY,
  WORK_ORDER_SERVER
} from '../api-common.config';

/**
 * 资产模块的接口路径常量
 */
export const FacilityRequestUrl = {
  // 查询设施列表不带分页查询
  queryDeviceBaseInfo: `${DEVICE_SERVER}/deviceInfo/queryDeviceBaseInfo`,
  // 根据部门code查区域信息
  listAreaByDeptCode: `${DEVICE_SERVER}/areaInfo/listAreaByDeptCode`,
  // 查询图片
  getPicDetailForNew: `${DEVICE_SERVER}/picRelationInfo/getPicDetailForNew`,
  // 根据区域查单位
  listDepartmentByAreaAndUserId: `${DEVICE_SERVER}/areaInfo/listDepartmentByAreaAndUserId`,
  // 根据区域code查询设备不带分页
  listEquipmentBaseInfoByAreaCode: `${DEVICE_SERVER}/equipmentInfo/listEquipmentBaseInfoByAreaCode`,
  // 查询区域树
  queryAreaBaseInfoList: `${DEVICE_SERVER}/areaInfo/queryAreaBaseInfoList`,
  // new查询区域树
  queryMigrationAreaBaseInfoList: `${DEVICE_SERVER}/areaInfo/queryMigrationAreaBaseInfoList`,
  // 获取设备列表
  equipmentListByPage: `${DEVICE_SERVER}/equipmentInfo/equipmentListByPage`,
  // 获取设备列表
  equipmentListByPageForListPage: `${DEVICE_SERVER}/equipmentInfo/equipmentListByPageForListPage`,
  // 获取网关配置已有设备列表
  queryConfigureEquipmentInfo: `${DEVICE_SERVER}/equipmentInfo/queryConfigureEquipmentInfo`,
  // 查询网关子集
  queryGatewaySubsetListByPage: `${DEVICE_SERVER}/equipmentInfo/gatewaySubsetListByPage`,
  // 根据设备型号获取设备配置项
  getEquipmentConfigByModel: `${DEVICE_SERVER}/equipmentProtocol/getThreshold`,
  // 根据设备id查询分组信息
  queryGroupInfoByEquipmentId: `${DEVICE_SERVER}/groupInfo/queryGroupInfoList`,
  // 查询分组详情中的设备列表
  queryGroupEquipmentInfoList: `${DEVICE_SERVER}/groupInfo/queryGroupEquipmentInfoList`,
  // 查询分组详情中的设施列表
  queryGroupDeviceInfoList: `${DEVICE_SERVER}/groupInfo/queryGroupDeviceInfoList`,
  // 设施列表
  deviceListByPage: `${DEVICE_SERVER}/deviceInfo/deviceListByPage`,
  // new设施列表
  deviceListByPageForListPage: `${DEVICE_SERVER}/deviceInfo/deviceListByPageForListPage`,
  // 上传设备图片
  uploadImageForLive: `${DEVICE_SERVER}/picRelationInfo/uploadImageForLive`,
  // 删除设备
  deleteEquipmentByIds: `${DEVICE_SERVER}/equipmentInfo/deleteEquipmentByIds`,
  // 查询实景图
  getPicDetail: `${DEVICE_SERVER}/picRelationInfo/getPicDetail`,
  // 根据设备id查询设备信息
  getEquipmentById: `${DEVICE_SERVER}/equipmentInfo/queryEquipmentInfoList`,
  // 查询设备日志
  queryEquipmentLog: `${DEVICE_SERVER}/deviceLog/deviceLogListByPage`,
  // 查询详情code值
  getDetailCode: `${DEVICE_SERVER}/equipmentProtocol/getDetailCode`,
  // 设施详情code值
  getDeviceDetailCode: `${DEVICE_SERVER}/deviceProtocol/getDetailCode`,
  // 查询设备绑定列表
  queryEquipmentBind: `${DEVICE_SERVER}/equipmentInfo/listSingleByCenterIdForPage`,
  // 档案编码唯一性校验
  queryEquipmentDocNumIsExist: `${DEVICE_SERVER}/equipmentInfo/queryEquipmentDocNumIsExist`,
  // 查询告警名称统计
  queryAlarmNameStatistics: `${ALARM_CURRENT_SERVER}/alarmStatistics/queryAlarmCurrentSourceName`,
  // 查询当前告警的级别统计
  queryCurrentAlarmLevelStatistics: `${ALARM_CURRENT_SERVER}/alarmStatistics/queryAlarmCurrentSourceLevel`,
  // 查询告警增量统计
  queryAlarmSourceIncremental: `${ALARM_CURRENT_SERVER}/alarmStatistics/queryAlarmSourceIncremental`,
  // 查询历史告警列表5条
  getAlarmHisInfoListById: `${ALARM_HISTORY_SERVER}/alarmHistory/queryAlarmHistoryEquipmentId`,
  // 历史告警名称统计
  queryAlarmHistorySourceName: `${ALARM_CURRENT_SERVER}/alarmStatistics/queryAlarmHistorySourceName`,
  // 历史告警级别统计
  queryAlarmHistorySourceLevel: `${ALARM_CURRENT_SERVER}/alarmStatistics/queryAlarmHistorySourceLevel`,
  // 查询当前告警列表5条
  getAlarmInfoListByEquipmentId: `${ALARM_CURRENT_SERVER}/alarmCurrent/queryAlarmEquipmentId`,
  // 设备配置详情
  queryEquipmentById: `${STRATEGY}/equipmentData/queryEquipmentById`,
  // new设备配置详情
  getEquipmentDataByType: `${STRATEGY}/equipmentData/queryEquipmentDataByType`,
  // 设备配置动态详情
  queryGatewayPropertyConfig: `${STRATEGY}/gateway/queryGatewayPropertyConfig`,
  // 查看应用策略信息
  queryStrategyListByRefId: `${DEVICE_SERVER}/strategy/listStrategyByCondAndEquipIdPage`,
  // 获取设备上报字段
  getSensor: `${DEVICE_SERVER}/equipmentProtocol/getSensor`,
  // 查询区域列表
  areaListByPage: `${DEVICE_SERVER}/areaInfo/areaListByPage`,
  // 根据部门id查区域信息
  selectAreaInfoByDeptIdsForView: `${DEVICE_SERVER}/areaInfo/selectAreaInfoByDeptIdsForView`,
  // 关联设施信息
  setAreaDevice: `${DEVICE_SERVER}/areaInfo/setAreaDevice`,
  // 查询统一授权范围
  deviceListOfLockByPage: `${DEVICE_SERVER}/deviceInfo/deviceListOfLockByPage`,
  // 查看设施详情
  queryDeviceInfo: `${DEVICE_SERVER}/deviceInfo/queryDeviceInfo`,
  // 获取配置策略配置项
  getPramsConfig: `${DEVICE_SERVER}/deviceConfig/getPramsConfig`,
  // 查询操作日志
  findOperateLog: `${LOG_SERVER}/log/findOperateLog`,
  // 查询设施类型数量
  queryDeviceTypeCount: `${DEVICE_SERVER}/statistics/queryDeviceTypeCount`,
  // 查询设备统计
  equipmentCount: `${DEVICE_SERVER}/statistics/queryEquipmentTypeCount`,
  // 查询回路详情
  queryLoopDetail: `${DEVICE_SERVER}/loopInfo/queryLoopDetail`,
  // 查询回路设施详情信息
  queryLoopDevicePageByLoopId: `${DEVICE_SERVER}/loopInfo/queryLoopDevicePageByLoopId`,
  // 移出回路
  moveOutLoop: `${DEVICE_SERVER}/loopInfo/moveOutLoopById`,
  // 最后一条设施日志的时间
  queryRecentDeviceLogTime: `${DEVICE_SERVER}/deviceLog/queryRecentDeviceLogTime`,
  // 根据工单id查询工单信息
  getProcessByProcId: `${WORK_ORDER_SERVER}/order/picture/getLocationTypeByProcId`,
  // 查询当前状态
  queryIsStatus: `${ALARM_CURRENT_SERVER}/alarmCurrent/queryIsStatus/`,
  // 根据设备型号获取设备配置项
  getEquipmentLockConfigByModel: `${LOCK_SERVER}/control/getControlBaseInfo`,
  // 根据设施ids分页查询回路列表
  loopListByPageByDeviceIds: `${DEVICE_SERVER}/loopInfo/loopListByPageByDeviceIds`,
  // 获取回路列表
  queryLoopListByPage: `${DEVICE_SERVER}/loopInfo/loopListByPage`,
  // 移入回路
  moveIntoLoop: `${DEVICE_SERVER}/loopInfo/moveInLoopById`,
  // 查询回路关联地图设施
  queryDeviceMapByLoop: `${DEVICE_SERVER}/loopInfo/queryLoopDeviceMap`,
  // 校验分组名称是否重复
  checkGroupInfoByName: `${DEVICE_SERVER}/groupInfo/checkGroupInfoByName`,
  // 查询分组列表
  queryGroupInfoList: `${DEVICE_SERVER}/groupInfo/queryGroupInfoList`,
  // 移除分组
  moveOutGroupById: `${DEVICE_SERVER}/groupInfo/moveOutGroupById`,
  // 修改分组信息
  updateGroupInfo: `${DEVICE_SERVER}/groupInfo/updateGroupInfo`,
  // 新增分组信息
  addGroupInfo: `${DEVICE_SERVER}/groupInfo/addGroupInfo`,
  // 获取杆型图
  getPoleInfoByDeviceId: `${DEVICE_SERVER}/poleInfo/getPoleInfoByDeviceId`,
  // 根据网关id获取传感器列表
  getSensorListByGatewayId: `${DEVICE_SERVER}/sensor/querySensorList`,
  // 设备批量配置
  equipmentBatchConfig: `${STRATEGY}/instruct/batchConfig`,
};
