import {DEVICE_SERVER, STRATEGY, WORK_ORDER_SERVER} from '../../../../core-module/api-service/api-common.config';

/**
 * 后端服务api路径常量
 */
export const EquipmentServiceUrlConst = {
  // 自动生成设备名称
  getEquipmentName: `${DEVICE_SERVER}/equipmentInfo/getEquipmentName`,
  // 查询设备名称是否已经存在
  queryEquipmentNameIsExist: `${DEVICE_SERVER}/equipmentInfo/queryEquipmentNameIsExist`,
  // 查询资产编码是否存在
  queryEquipmentCodeIsExist: `${DEVICE_SERVER}/equipmentInfo/queryEquipmentCodeIsExist`,
  // 根据设备id查询设备信息
  getEquipmentById: `${DEVICE_SERVER}/equipmentInfo/queryEquipmentInfoList`,
  // 增加设备
  addEquipment: `${DEVICE_SERVER}/equipmentInfo/addEquipment`,
  // 修改设备
  updateEquipmentById: `${DEVICE_SERVER}/equipmentInfo/updateEquipment`,
  // 删除设备
  deleteEquipmentByIds: `${DEVICE_SERVER}/equipmentInfo/deleteEquipmentByIds`,
  // 根据设施id查询挂载位置
  findMountPositionById: `${DEVICE_SERVER}/poleInfo/findMountPositionById`,
  // 根据设备类型查询设备型号信息
  getDeviceModelByType: `${DEVICE_SERVER}/deviceInfo/getDeviceModelByType`,
  // 查询网关端口
  queryGatewayPort: `${DEVICE_SERVER}/equipmentPortLiveInfo/queryEquipmentPort`,
  // 撤回工单
  revokeProc: `${WORK_ORDER_SERVER}/revokeProc`,
  // 上传设备图片
  uploadImageForLive: `${DEVICE_SERVER}/picRelationInfo/uploadImageForLive`,
  // 查询设备模型的详细卡片code
  getDetailCode: `${DEVICE_SERVER}/equipmentProtocol/getDetailCode`,
  // 查询网关端口拓扑
  queryGatewayPortInfoTopology: `${DEVICE_SERVER}/gatewayPortInfo/queryGatewayPortInfoTopology`,
  // 查询网关端口拓扑new
  queryEquipmentPortInfoTopology: `${DEVICE_SERVER}/equipmentPortLiveInfo/queryEquipmentPortInfoTopology`,
  // 删除连线关系
  deleteEquipmentPortLiveInfo: `${DEVICE_SERVER}/equipmentPortLiveInfo/deleteEquipmentPortLiveInfo`,
  // 保存网关端口拓扑
  saveGatewayPortInfo: `${DEVICE_SERVER}/gatewayPortInfo/saveGatewayPortInfo`,
  saveEquipmentPortLiveInfo: `${DEVICE_SERVER}/equipmentPortLiveInfo/saveEquipmentPortLiveInfo`,
  // 清除网关端口信息
  deleteGatewayPortInfo: `${DEVICE_SERVER}/gatewayPortInfo/deleteGatewayPortInfo`,
  // 拖动设备位置
  updateEquipmentPosition: `${DEVICE_SERVER}/equipmentPortLiveInfo/updateEquipmentPosition`,
  // 修改连线信息
  updateLineName: `${DEVICE_SERVER}/equipmentPortLiveInfo/updateLineName`,
  // 修改节点信息
  updateNodeName: `${DEVICE_SERVER}/equipmentPortLiveInfo/updateNodeName`,
  // 获取网关配置已有设备列表
  queryConfigureEquipmentInfo: `${DEVICE_SERVER}/equipmentInfo/queryConfigureEquipmentInfo`,
  // 根据设备型号获取设备配置项
  getEquipmentConfigByModel: `${DEVICE_SERVER}/equipmentProtocol/getThreshold`,
  // 根据设施id查询回路的信息
  loopListByDeviceIds: `${DEVICE_SERVER}/loopInfo/loopListByDeviceIds`,
  // 根据设备id查查询分组信息
  queryGroupInfoByEquipmentId: `${DEVICE_SERVER}/groupInfo/queryGroupInfoByEquipmentId`,
  // 查询权限区域
  queryAreaListForPageSelection: `${DEVICE_SERVER}/areaInfo/areaListByPage`,
  // 导出设备数据
  exportEquipmentData: `${DEVICE_SERVER}/equipmentInfo/exportEquipmentList`,
  // 下载批量导入模板
  downloadTemplate: `${DEVICE_SERVER}/equipmentInfo/downloadTemplate`,
  // 批量导入
  batchImportEquipmentInfo: `${DEVICE_SERVER}/equipmentInfo/batchImportEquipmentInfo`,
  // 设备配置保存
  instructDistribute: `${STRATEGY}/instruct/instructDistribute`,
  // 校验设备id的唯一性
  querySequenceIdIsExist: `${DEVICE_SERVER}/equipmentInfo/querySequenceIdIsExist`,
  // 校验平台id的唯一性
  queryEquipmentPlatformIdIsExist: `${DEVICE_SERVER}/equipmentInfo/queryEquipmentPlatformIdIsExist`,
  // 根据集控id查询回路信息
  queryLoopInfoByCentralizedId: `${DEVICE_SERVER}/loopInfo/queryLoopInfoByCentralizedId`,
  // 根据集控id 获取回路下的单控总数
  queryLoopSingleNumByCenterId: `${DEVICE_SERVER}/loopInfo/queryLoopSingleNumByCenterId`,
  // 查询回路和线缆的绑定关系
  queryLoopCableInfo: `${DEVICE_SERVER}/loopCable/queryLoopCableInfo`,
  // 单控和线缆的关系
  querySingLightAndCableRelation: `${DEVICE_SERVER}/loopCable/querySingLightAndCableRelation`,
  // 查询传感器名字是否存在
  querySensorNameIsExist: `${DEVICE_SERVER}/sensor/checkNameOnly`,
  // 新增传感器
  createSensor: `${DEVICE_SERVER}/sensor/createSensor`,
  // 修改传感器配置
  updateSensor: `${DEVICE_SERVER}/sensor/updateSensor`,
  // 查询传感器详情
  querySensorDetail: `${DEVICE_SERVER}/sensor/sensorDetail`,
  // 删除网关上传感器
  deleteSensor: `${DEVICE_SERVER}/sensor/deleteSensor`,
  // 批量获取传感器基础信息
  querySensorInfoList: `${DEVICE_SERVER}/sensor/querySensorInfoList`,
  // 获取上传信息value
  getEquipmentDataByType: `${STRATEGY}/equipmentData/queryEquipmentDataByType`,
};
